<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>RepoDoctor.Core</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Catalog\catalog.v1.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.FileSystemGlobbing" />
  </ItemGroup>

</Project>
