// <auto-generated/>
using System;

namespace EditorConfigMatrix.Generated;

public sealed class Machine
{
    public void Rethrow()
    {
        try
        {
            Work();
        }
        catch (Exception ex)
        {
            throw ex;
        }
    }

    private static void Work()
    {
    }
}
